GET https://fullstack-open-hwez.onrender.com/api/persons/
###
POST https://fullstack-open-hwez.onrender.com/api/persons/ 
content-type: application/json

{
    "name": "Smeagol Heagol",
    "number": "19748230"
}